### ISSUE TITLE
Compatible With `factor-bundle` plugin?

### ISSUE THREAD

**Issue by cdaringe** [ben-ng/minifyify#100]
Hello:

Is it possible to use this plugin in conjunction with substack's [factor-bundle](https://github.com/substack/browserify-handbook#factor-bundle)?

**Comment by ben-ng** [comment]
Nope, sorry.

**Comment by cdaringe** [comment]
bummer, thx.  minifyify was good while it lasted!

**Comment by cdaringe** [comment]
really appreciated your work here!

**Comment by ben-ng** [comment]
Thanks! We use factor-bundle too at my work, so its something I need as well. It just hasn't been as important as my other tasks.

**Comment by cdaringe** [comment]
word.  do you guys get good `watch/watchify` perf when using factor-bundle.  Mine's takes ~7s on each bundle, even w/ caching.  what's your minify strategy now that you've gone to a multi-bundle approach?  No more barrage of questions :smile:

**Comment by ben-ng** [comment]
Our bundles take over 15s with caching. We haven't found a very good solution yet. Some people say Webpack is great, but I haven't tried it.

I've done some experimentation with a [multithreaded, native port of browserify](https://github.com/ben-ng/paq) and saw a 4x speedup. Not sure if it's a viable solution moving forward, though.
