### ISSUE TITLE
Inline sourcemap

### ISSUE THREAD

**Issue by youngroger** [ben-ng/minifyify#105]
Hi, 

Is there a possibility to inline sourcemaps? In the example below tsify passes the sourcemap from the original TypeScript files on to Browserify, but minifyify seems to extract the sourcemap from the bundle.js, and somehow ends up not working.

```JavaScript
gulp.task('javascript', function() {
	return browserify({ debug: true })
		.add("src/main.ts")
		.plugin('tsify')
		.plugin('minifyify', {map: '/js/bundle.min.map', output: 'public/js/bundle.min.map' })
		.bundle()
		.pipe(fs.createWriteStream(public/js/bundle.js));
});
```

**Comment by ben-ng** [comment]
if you want to inline sourcemaps you should just use browserify without minifyify. if you inline the minifyify sourcemap you'll end up with an even bigger bundle than if you had just used browserify.

you should probably figure out why the external sourcemap isn't working instead.

**Comment by youngroger** [comment]
Thats true, you're right.

**Comment by TehShrike** [comment]
It would make my build process cleaner if source maps were inlined throughout my entire browserify pipeline until I was ready to write the source out to a file and would then split it up with something like [exorcist](https://www.npmjs.com/package/exorcist).
