### ISSUE TITLE
Does this actually not support Browserify 0.11?

### ISSUE THREAD

**Issue by distracteddev** [ben-ng/minifyify#106]
The docs say it supports up to Browserify v0.9. Is this for any particular reason or simply that it hasn't been tested with the latest Browserify version?

**Comment by ben-ng** [comment]
just untested. it probably works! i'd love a pr that runs our tests up to 11. should be a two liner.

**Comment by distracteddev** [comment]
@ben-ng This line in the `npm run test` output makes me think it already does:

`[test-peer-range] Testing browserify versions 5, 6, 7, 8, 9, 10, 11`

**Comment by ben-ng** [comment]
you're right, i think we just need a doc update then :+1:

**Comment by distracteddev** [comment]
Also, I see the note about coffeeify, I think that might be out of date as well. How would I go about re-enabling those tests?

**Comment by distracteddev** [comment]
Also, all tests passed on v10 and v11, so yes, only doc update is needed.

**Comment by ben-ng** [comment]
Those tests were commented out in https://github.com/ben-ng/minifyify/blob/master/test/bundles.js#L198
