### ISSUE TITLE
Support browserify 12?

### ISSUE THREAD

**Issue by asadovsky** [ben-ng/minifyify#110]
Browserify is now at version 12, but the minifyify README.md says "Supports up to Browserify 11". Does the latest minifyify support Browserify 12?

**Comment by asadovsky** [comment]
It worked for my project, but perhaps my project doesn't make extensive use of the browserify / minifyify functionality. Seems it'd be better to run the tests (from the test dir) with the new version of browserify, and only bump the "works with" line if those tests pass?

**Comment by hamczu** [comment]
just FYI: I'm using it with Browserify 13 with no issues

**Comment by ben-ng** [comment]
thanks, I removed the "supports up to..." line in the readme and added tests up to the latest version.
