### ISSUE TITLE
Disable Compression

### ISSUE THREAD

**Issue by aristidesfl** [ben-ng/minifyify#115]
Is it possible to disable compression entirely so that debugger statements are not removed?

**Comment by ben-ng** [comment]
Yes, it should be documented in the readme.

**Comment by aristidesfl** [comment]
It should be? 
Or is already?

**Comment by ben-ng** [comment]
[here it is](https://github.com/ben-ng/minifyify#optionsminify)

(I was on mobile at the time or I would have linked you directly)

**Comment by aristidesfl** [comment]
I'm looking to disable compression `-c, --compress Enable compressor/pass compressor options`,  not minification entirely.

**Comment by ben-ng** [comment]
if its an uglify option, you can specify those in an `uglify` option and minifyify will forward it on to uglify.

See the command line [docs](https://github.com/ben-ng/minifyify#command-line)

**Comment by aristidesfl** [comment]
The problem is that minify already passes the `--compress` option. I need a way to omit this option. As far as I know you can't do `--compress false`.

**Comment by ben-ng** [comment]
That's a bug, a fix is going up now. Nice find!

**Comment by ben-ng** [comment]
Fixed in 7.3.0. Please try that?

**Comment by aristidesfl** [comment]
`false` is not a valid value for the `uglify --compress` option, its not possible to disable compression that way, only by omitting the `--compress` flag

**Comment by aristidesfl** [comment]
This is the command I'm using with 7.3.0:
```
browserify --debug test.coffee -t coffeeify -p [ minifyify --map test.map.json --output test.map.json ]
```

**Comment by ben-ng** [comment]
According to [this issue](https://github.com/mishoo/UglifyJS2/issues/696), it is in fact not compressing, but you need to "beautify" the output with an additional option. So this has nothing to do with minifyify at all, it just forwards options to uglify.

I have added [a test](https://github.com/ben-ng/minifyify/blob/master/test/bundles.js#L238) that verifies that this is working.

The command should now be something like this:

```
browserify entry.js -d -p [minifyify --map bundle.map.json --output bundle.map.json --uglify [ --output [ --beautify ] --compress false ] ] > bundle.js
```

**Comment by aristidesfl** [comment]
When I run that command I get `uglify-js failed on entry.js : Error`
If I try to do `uglify --compress false` I also get `Error parsing arguments in: false`

**Comment by aristidesfl** [comment]
Are you sure your tests are not passing just because uglify is simply not being run?

**Comment by ben-ng** [comment]
I think your problem lies in Browserify's argument parser. Minifyify doesn't parse arguments, you need to check in Browserify to see how to correctly pass the right information.

Uglify is definitely being run -- if I remove the "beautify" option the newlines are removed.

Have you tried using the programmatic browserify API, like in the tests?

**Comment by aristidesfl** [comment]
That seems to work, have you tried the command line you provided? Which test file are you using?

**Comment by ben-ng** [comment]
I did not try the command line I provided. I don't use browserify on the command line so I was just giving a guess at it. You should go on the browserify project and ask them for help with that.
