### ISSUE TITLE
Error in compiled JS when using node-source-map-support

### ISSUE THREAD

**Issue by dumbmatter** [ben-ng/minifyify#116]
See https://github.com/dumbmatter/minifyify-node-source-map-support-bug for a simple test case. Below I'm just repeating the README.md I made for that repo:

There appears to be some conflict between [`node-source-map-support`](https://github.com/evanw/node-source-map-support) and [`minifyify`](https://github.com/ben-ng/minifyify). `app.js` contains the simplest usage of `node-source-map-support`:

    require('source-map-support');
    console.log('Success!');

Compile it both with and without `minifyify` by running `npm run build` (precompiled versions are in the `dist` folder).

Then you can test it by running `npm test` or opening the two .html files in your browser and looking at the console. The version without minifyify works, but the version with minifyify results in an error:

    Error: Cannot find module './base64-vlq'
        at Function.Module._resolveFilename (module.js:325:15)
        at Function.Module._load (module.js:276:25)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at s (/home/jdscheff/projects/minifyify-node-source-map-support-bug/dist/app-with-minifyify.js:1:176)
        at /home/jdscheff/projects/minifyify-node-source-map-support-bug/dist/app-with-minifyify.js:1:367
        at l (/home/jdscheff/projects/minifyify-node-source-map-support-bug/dist/app-with-minifyify.js:31:1675)
        at o (/home/jdscheff/projects/minifyify-node-source-map-support-bug/dist/app-with-minifyify.js:31:1181)
        at Object.<anonymous> (/home/jdscheff/projects/minifyify-node-source-map-support-bug/dist/app-with-minifyify.js:26:280)
        at u (/home/jdscheff/projects/minifyify-node-source-map-support-bug/dist/app-with-minifyify.js:31:815)

**Comment by ben-ng** [comment]
I have no idea what's causing this, but before I look into it, is it necessary to have source map support in your browser build? Even if we figured out what's going wrong here, it seems like you don't want that module required in the browser anyway. If possible, i would just ignore that module using the `browser` package.json field so it doesn't get bundled in the first place.

**Comment by dumbmatter** [comment]
Sadly I do want it in my browser build, because [otherwise Bluebird+Browserify+Source Maps does not work very well](https://github.com/petkaantonov/bluebird/issues/363). But with `source-map-support` it works quite well.

Also thanks for your work on this project, I've been using `minifyify` for a little while now and it's worked perfectly except for this one little issue.

**Comment by ben-ng** [comment]
Huh, how interesting. I use bluebird and browserify myself. I'm not sure what we're doing differently -- my source maps seem to be fine.

**Comment by dumbmatter** [comment]
If you figure that out, let me know! I imagine browsers will fix it eventually, but I'm still having the issue in the latest version of Chrome.

**Comment by wildtangent** [comment]
Hi
I just came across this same issue, however I am not using source-map-support or bluebird

I just swapped to minifyify from uglify 

```
gulp = require 'gulp'
plugins = require('gulp-load-plugins')()
args = require('yargs').argv
browserify = require 'browserify'
watchify = require 'watchify'
source = require 'vinyl-source-stream'

gulp.task 'browserify', ['watch'], ->
  bundler = browserify
    entries: ['./src/scripts/main.coffee']
    extensions: ['.coffee']
    debug: true,
    cache: {}, packageCache: {}

  bundler.transform 'coffeeify'

# With this block commented out its OK
  bundler.plugin 'minifyify',
    map: 'app.js.map'
    output: './dist/scripts/app.js.map'

  watcher  = watchify bundler
  watcher
  .on 'update', ->
      updateStart = Date.now()
      plugins.notify 'Bundling started'
      watcher
      .bundle()
      .on 'error', plugins.notify.onError (error)->
        return "Browserify Error: #{error.message}"
      .pipe source 'main.js'
      .pipe(plugins.rename('app.js'))
      .pipe gulp.dest './dist/scripts/'
      plugins.notify 'Bundle finished!', ((Date.now() - updateStart) + 'ms')
  .bundle()
  .pipe source 'app.js'
  .pipe gulp.dest './dist/scripts/'
```

**Comment by dumbmatter** [comment]
After some more Googling, I think I figured out a workaround. @ben-ng I just need a tiny bit more help to figure out how to implement it!

It's the same issue as [this](https://github.com/hughsk/uglifyify/issues/40). I just need to figure out how to pass that option to minifyify. If I go into your code and right before [this line](https://github.com/ben-ng/minifyify/blob/9dfa1d6272ed02cc7b21e2073109ddc6e71447f4/lib/minifier.js#L179) put:

    opts.mangle = {except: ['require']};

then my problem goes away.

And I know you support passing uglify options on the command line, but I can't figure it out. The closest I got was:

    $ browserify -p [ minifyify --no-map --uglify [ --mangle [ --except require ] ] ] app.js -o dist/app-with-minifyify.js

which sets `opts.mangle.except` to `'require'`. However I need it to be `['require']`. I tried [the methods described here for passing arrays to browserify through the command line](https://github.com/substack/node-browserify/issues/779), but did not succeed. Any ideas?

**Comment by ben-ng** [comment]
Awesome that you figured out what's wrong. Unfortunately I can't help much because I have never used the browserify CLI's option passing thing; it always seemed really opaque to me. You're better off asking for help there.

**Comment by dumbmatter** [comment]
I ended up just using the JS API like:

    bundler.plugin('minifyify', {
        uglify: {
            // https://github.com/ben-ng/minifyify/issues/116
            mangle: {
                except: ['require']
            }
        },
        ...
    });

That works for me, and should help anyone with the same problem. So I'm going to close this issue, since the actual "problem" (if it even exists) probably lies in either node-source-maps or uglify, not this project.

**Comment by shadinger** [comment]
Thanks a lot, it solved my problem too.

I found a workaround for the CLI to work:

`$ browserify -p [ minifyify --no-map --uglify [ --mangle [ --except require --except require ] ] ] app.js -o dist/app-with-minifyify.js`

This sets `opts.mangle.except` to `['require','require']` which works perfectly.
