### ISSUE TITLE
Use .js.map instead of .map.json

### ISSUE THREAD

**Issue by axelpale** [ben-ng/minifyify#117]
[Source map format proposal revision 3](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.9ppdoan5f016) says under title "[Conventions](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.txk3vdsh99hf)":

> Optionally, a source map will have the same name as the generated file but with a “.map” extension.  For example, for “page.js” a source map named “page.js.map” would be generated.

I guess minifyify documentation should follow this convention too.

**Comment by ben-ng** [comment]
Sure, send me a pull request? I didn't know this was a thing.

**Comment by axelpale** [comment]
Great, I try to send one later this week.

**Comment by ben-ng** [comment]
Thanks :+1:
