### ISSUE TITLE
"better-maintained alternatives"?

### ISSUE THREAD

**Issue by mrDarcyMurphy** [ben-ng/minifyify#128]
You mentioned using "better-maintained alternatives" in the README. Any suggestions?

**Comment by ben-ng** [comment]
Sorry, I don't have any -- I've been out of touch for too long!

**Comment by mrDarcyMurphy** [comment]
It's all good. I found what I needed in [`grunt-exorcise`](https://www.npmjs.com/package/grunt-exorcise). Hope it works for other people too.
