### ISSUE TITLE
Not working with transforms?

### ISSUE THREAD

**Issue by jescalan** [ben-ng/minifyify#28]
Ah, while I thought my problems had been solved, I almost immediately ran into another one. I'm trying to use the coffeeify transform here to load in coffee files, but as soon as I introduce minifyify, another error comes up.

Reproduction code:

``` coffee
# index.coffee
console.log 'wow'
```

``` js
// test.js
var path   = require('path'),
browserify = require('browserify'),
coffeeify  = require('coffeeify'),
minifyify  = require('minifyify');

var b = browserify({ extensions: ['.js', '.json', '.coffee'] });
b.transform(coffeeify)
b.add(path.join(__dirname, 'index.coffee'));
b.bundle({debug: true}).pipe(minifyify()).pipe(process.stdout);
```

The error I'm getting looks like this:

```
return cb(new Error('Nothing to optimize. Did you set debug to true, and
             ^
TypeError: undefined is not a function
  at Stream.end (xxx/node_modules/minifyify/lib/index.js:33:14)
```

If I remove minifyify, it works, and if I change the coffee file to javascript and remove the transform, it works. Thanks again for being so responsive and for your great work on this library!

**Comment by polkovnikov-ph** [comment]
@ben-ng 

> to clarify, are you using minifyify as a plugin or transform? it's a plugin.

I recognize the fact that I'm stupid, but I've already been into this issue twice. Could you add a bit more explicit message into `README.md`?
