### ISSUE TITLE
Grunt integration with https://npmjs.org/package/grunt-browserify

### ISSUE THREAD

**Issue by ahinz** [ben-ng/minifyify#5]
I played around a bit and kept getting 'Fatal Error: Invalid Mapping'. If you have time or ideas about how to call minifyify from grunt via browserify I'm all ears!

This is totally an enhancement, not a bug!

**Comment by cdaringe** [comment]
@piranna, nm!  this may not be the right venue, but can someone comment on my config?  my `map` file is not being generated.  i dont think the `minifyify` options get passed through like they do with transforms.

```js
ampersand: {
    files: {
        'amp.bundle.min.js': [
            "js/browserApp/app.js",
            "js/dataType/Error.js"
        ]
    },
    options: {
        browserifyOptions: {
            debug: true
        },
        plugin: [
            ['minifyify', {
                map: './amp.bundle.map.json' // have tried toying with the path to no success
            }]
        ]
    }
},
```

**Comment by cdaringe** [comment]
Yahoo!  Answered my own question. The target's option's plugin `[]` looks like below.  I didn't know that if you provide a function, an instance of browserify gets passed to the function, and you can use the node-browserify api!  I was also missing an `output` attr.

```js
options: {
            plugin: [
                [function(b) {
                    b.plugin('minifyify', {
                        map: 'coins_core/build/js/browser.bundle.map.json',
                        output: './build/js/browser.bundle.map.json'
                    });
                }],
            ],
```
