### ISSUE TITLE
Issue with bundle() that no longer accepts option arguments

### ISSUE THREAD

**Issue by Zielun** [ben-ng/minifyify#52]
I get

```
node_modules/gulp/node_modules/orchestrator/index.js:153
            throw err;
                  ^
Error: bundle() no longer accepts option arguments.
Move all option arguments to the browserify() constructor.
```

although I don`t pass arguments to bundle();

```
gulp.task('build', function() {
var b = new browserify();

        b.add('./main.js');

        b.plugin('minifyify', {
            map: false,
            minify: false,
            output: './bundle.map.js'
        });

        b.bundle();
})
```

**Comment by nicholasmordecai** [comment]
In case anybody else comes across this issue, I got it working with:

> gulp.task('browserify', function() {
    var b = new browserify({debug: true});
    return b.add("src/js/main.js")
        .bundle()
        .pipe(source('game.js'))
        .pipe(gulp.dest('public/js'), {overwrite: true})
        .pipe(gulp.dest('dist', {overwrite: true}));
});
