### ISSUE TITLE
source maps return the minified source code

### ISSUE THREAD

**Issue by tinyels** [ben-ng/minifyify#54]
This was working in the way I expected last week, but now I get this result in a clean copy of my repo

`browserify -d scripts/main.js -p [minifyify --map bundle.map --output scripts/bundle.map] -o scripts/bundle.js`

produces minified bundle.js but the mapping gives me minified code in the debugger. 
![sourcemap](https://cloud.githubusercontent.com/assets/3142631/3739160/5b7d341c-1748-11e4-84aa-132e1c9045f2.png)

**Comment by llaski** [comment]
Want to note I was using 4.4.0 and was experiencing the same issue. Once I upgraded to 6.1.0 it worked fine so not sure if something else was affecting this.
