### ISSUE TITLE
A bit lost with Gulp + Browserify/Watchify + Coffeeify + Minifyify

### ISSUE THREAD

**Issue by rayosgod** [ben-ng/minifyify#58]
I get the following error when I try to enable the Minifyify plugin:

`[02:43:06] 'browserify' errored after 241 ms Minifyify: opts.output is required since no callback was given
`

I would like to minify the output of the coffeeify while preserving the source map. The script is adapted from https://github.com/greypants/gulp-starter/blob/master/gulp/tasks/browserify.js.

If I understand properly, I should add a callback to `bundler.bundle({debug:true})`, but I don't know what to do in it...

``` CoffeeScript
browserify   = require 'browserify'
watchify     = require 'watchify'

gulp         = require 'gulp'

source       = require 'vinyl-source-stream'
buffer       = require 'vinyl-buffer'

uglify       = require 'gulp-uglify'
minifyify    = require 'minifyify'

bundleLogger = require '../util/bundleLogger'
handleErrors = require '../util/handleErrors'


gulp.task 'browserify', ->
  bundleMethod = if global.watching then watchify else browserify

  bundler = bundleMethod
    # Specify the entry point of your app
    entries: ['./client/js/main.coffee'],
    # Add file extentions to make optional in your requires
    extensions: ['.coffee'],
    debug: !global.production

  bundler.transform("coffeeify")#!!global.production ? "coffeeify/no-debug" : "coffeeify")
  bundler.plugin('minifyify')

  bundle = ->
    # Log when bundling starts
    bundleLogger.start()

    bundler
      # Enable source maps!
      .bundle({debug:true})
      # Report compile errors
      .on('error', handleErrors)
      # Use vinyl-source-stream to make the
      # stream gulp compatible. Specifiy the
      # desired output filename here.
      .pipe(source 'app.js')

      # This works, but eats the source map.
      # .pipe(buffer())
      # .pipe(uglify())

      # Specify the output destination
      .pipe(gulp.dest './static/scripts')
      # Log when bundling completes!
      .on('end', bundleLogger.end)

  if global.watching
    # Rebundle with watchify on changes.
    bundler.on 'update', bundle


  bundle()
```

_Edit: I should probably add that Coffeeify inlines the source map at the end of the bundle._

**Comment by MatthewHerbst** [comment]
@ben-ng why do we also need to specify `output` if we give `map`? The docs clearly state that `output` is only required if running from the CLI, and is option when using Minifyify programatically.

**Comment by ben-ng** [comment]
`map` isn't where to write the file to disk. `map` is the `sourceMappingURL` path that is added to the minified code.

`output` is where to write the file to disk. its an option when working programmatically, because you can provide a callback, which will use the signature `cb(err, src, map)`. However, if you don't provide one, you need to tell minifyify where to write the map file to.
