### ISSUE TITLE
Since 4.1.2, weird code is added to the stdout

### ISSUE THREAD

**Issue by jeromegn** [ben-ng/minifyify#72]
Working with the latest I noticed this is prepended to my minified source:

```javascript
{ '0': 
   { files: [ [Object] ],
     exports: {},
     _pending: 0,
//...
```

This is invalid javascript.

I installed 4.1.1 specifically and it's not there anymore.

**Comment by ben-ng** [comment]
Please reopen this issue if the problem persists with minifyify@5.0.0
