### ISSUE TITLE
Sourcemap displays as single line and partially minified

### ISSUE THREAD

**Issue by pselden** [ben-ng/minifyify#74]
I'm trying out minifify to generate external sourcemaps and ran into an issue with the file that is displayed in my browser.

It appears that parts of the files are already partially minified (and displayed as a single line).

I was able to reproduce it with a small test case: https://github.com/pselden/minifyify-problem

![screen shot 2014-10-27 at 3 51 33 pm](https://cloud.githubusercontent.com/assets/709282/4798331/b6fc4a06-5e12-11e4-88a1-0111c905b547.png)

(formatted)
![screen shot 2014-10-27 at 3 51 41 pm](https://cloud.githubusercontent.com/assets/709282/4798334/b9d21936-5e12-11e4-8281-4dadc05b662a.png)

The original file is here: https://github.com/pselden/minifyify-problem/blob/master/app.js

Notice that it's partially minified (function names are preserved), but the parameters are minified and the entire thing is on one line.

```
browserify -v
6.2.0

browserify app.js -d -p [minifyify --map bundle.map.json --output bundle.map.json] > bundle.js
```

Could it be that my browserify is version 6 -- I see your repo says it supports version 5?

**Comment by ben-ng** [comment]
Should be resolved in bf5fd9b3cc9ce4042668286236840d536e0c6b41

New version on npm: 5.0.0

Let me know if it works.

**Comment by tobiastom** [comment]
Seems to work very nicely now. Thank you @ben-ng

**Comment by ben-ng** [comment]
Excellent! Thanks for reporting back.

**Comment by pselden** [comment]
Thanks! Working for me too.
