### ISSUE TITLE
.json requires are not minified

### ISSUE THREAD

**Issue by jfirebaugh** [ben-ng/minifyify#76]
I'm converting a project from a build system that piped browserify output to uglifyjs to minifyify, and the bundle is getting slightly bigger. The main cause seems to be .json files not being minified. I would expect non-significant whitespace in required json files to be removed, but it doesn't seem to be. For example: https://gist.github.com/jfirebaugh/817c255eb1e84528d462

With `browserify index.js -d -p [minifyify --map bundle.map.json --output bundle.map.json]`, I would expect the output to include something like:

[function(require,module,exports){
module.exports={"foo":"bar"}
},{}]

But it looks like:

```
[function(require,module,exports){
module.exports={
    "foo": "bar"
}
},{}]
```

I.e. the indenting spaces and the space between `:` and the value are still present.

**Comment by ben-ng** [comment]
6.1.0 now does JSON magnification

**Comment by jfirebaugh** [comment]
Upgraded, thank you! :+1:
