### ISSUE TITLE
Non-standard use of bundle() callback leads to clash in grunt-browserify

### ISSUE THREAD

**Issue by ccprog** [ben-ng/minifyify#77]
This grunt config:
```javascript
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    licence: grunt.file.read('./LICENCE'),
    browserify: {
      options: {
        banner: '/*\n<%= licence %>*/\n',
        plugin: [ [ 'minifyify', {map: false } ] ],
      },
      mini: {
        src: 'index.js',
        dest: '<%= pkg.name %>.bundle.mini.js'
      },
    }
  });
```
ends with a `Fatal error: [bundle]  has no method 'copy'`, [bundle] beeing the completed and minified bundle. The bundle code dumped with the message seems to be otherwise working correctly.

Using either one of both options works just fine.

@tleunen [answered](/jmreidy/grunt-browserify/issues/279) for grunt-browserify:
> It's an issue with `minifyify`. You should ask @ben-ng to change how `minifyify` works.
> By default, the function [.bundle()](/substack/node-browserify#bbundlecb) in browserify takes a function callbacks with 2 parameters,
> an error and a buffer.
>
> When `minifyify` is used, the buffer parameter is not a Buffer object but a string, which causes
> `grunt-browserify` to throw an error when it tries to prepend the banner to the buffer.
> Of course, we could fix it on our side, but `minifyify` should not change the way browserify works.
>
> The issue seems to be at [this line in `minifyify`](/ben-ng/minifyify/blob/master/lib/index.js#L85). So instead of str, it should be `new Buffer(str)`.

**Comment by ben-ng** [comment]
Thank you so much! This has been published as 6.0.0 because it is a breaking change.
