### ISSUE TITLE
Error trying to use minifyify on any of programmatic or command-line mode

### ISSUE THREAD

**Issue by AndrewKovalenko** [ben-ng/minifyify#78]
I use:
*  "browserify": "^8.1.0"
*  "gulp": "^3.8.10"
*  "minifyify": "^6.0.0"

everything is installed from npm.

if I try to run task
```
gulp.task('js:build-scripts', function() {
  return browserify({
    debug: true,
    entries: ['./src/js/index.js']
  }) 
  .plugin('minifyify', {
    map: 'application.js.map',
    output: 'application.js.map'
  })
  .bundle()
  .pipe(plumber({
    errorHandler: function(error) { console.log(error); }
  }))
  .pipe(gulp.dest('build/js'))
  ;
});
```

I receive an error:
```
Error: not implemented
    at Readable._read (_stream_readable.js:444:22)
    at Readable.read (_stream_readable.js:321:10)
    at resume_ (_stream_readable.js:705:12)
    at _stream_readable.js:697:7
    at process._tickCallback (node.js:337:11)
    at Function.Module.runMain (module.js:489:11)
    at startup (node.js:111:16)
    at node.js:809:3
````

Exactly the same error I receive if I try to build bundle from command-line using `browserify src/js/index.js -d -p [minifyify --map application.js.map --output application.js.map] > index.js`

**Comment by ben-ng** [comment]
Does this also happen with the last version 5? There was a breaking change in 6 that might have caused this.

**Comment by chunpu** [comment]
same problem "not implemented" !

**Comment by enahum** [comment]
I also had the same problem "not implemented" when used with node 0.12.0, running on node 0.10.35 worked fine.

**Comment by ben-ng** [comment]
Oh, interesting. Thanks for letting me know that it doesn't work on node 0.12.

**Comment by mariusk** [comment]
Yes, confirmed, works with node 0.10.36, but not 0.12.

**Comment by GentlemanHal** [comment]
I've also hit this issue

**Comment by asadovsky** [comment]
Same here. Works in Node 0.10.33, not in 0.12.0.

**Comment by ben-ng** [comment]
This is on npm as 6.1.1 and [tested on 0.12, 0.10, and io.js](https://travis-ci.org/ben-ng/minifyify/builds/51061997).

Side note: its amazing how long I've been using node without actually understanding streams/streams2/streams3. This issue forced me to figure out how they worked.
