### ISSUE TITLE
Drop Debugger Pass Thru Not Functioning

### ISSUE THREAD

**Issue by cdaringe** [ben-ng/minifyify#85]
It doesn't appear that `drop_debugger` is working successfully.  Any tips?
```js
plugin: [
    [function(b) {
        b.plugin('minifyify', {
            map: '/coins_core/build/js/browser/amp.bundle.map.json',
            output: './build/js/browser/amp.bundle.map.json',
            uglify: {
                drop_debugger: false
            }
        });
    }]
],
```

**Comment by NicolasZanotti** [comment]
You need to pass that within the compress object.

	uglify: {
		map: '',
		output: '',
		compress: {
			drop_debugger: true
		}
	}

Check the Uglify documentation under [The simple way](https://github.com/mishoo/UglifyJS2#the-simple-way) for more examples.

**Comment by cdaringe** [comment]
dang it, of course.  THanks @NicolasZanotti!
