### ISSUE TITLE
sourceMap loads, developer tools vars still mangled

### ISSUE THREAD

**Issue by cdaringe** [ben-ng/minifyify#91]
Hi all:

This is a question, not necessarily a bug.  See attached.
![screen shot 2015-04-01 at 5 58 41 pm](https://cloud.githubusercontent.com/assets/1003261/6956024/2201e6c2-d89c-11e4-84c5-fe9712c9d570.png)

See the var `details`.  Details is shown, but in the console, `details` is not shown in scope.  A mangled version probably is, as are the mangled args (e.g. `a`, `c`, `l`, etc).

Do folks know how to get the original vars mapped, s.t. I can use them in the console?  Hovering for inspection, for example, won't work.

Thanks!

Chris

**Comment by ben-ng** [comment]
i don't know if there is a way to map the variables back to their original names. one quick and dirty option is to tell uglify to stop mangling names. minifyify lets you pass options through to uglify for things like this.

**Comment by cdaringe** [comment]
Thanks Ben!  I found a dupe question here https://groups.google.com/forum/m/#!topic/google-chrome-developer-tools/EPG4T_Q_LNQ

**Comment by cdaringe** [comment]
Ben, have you been able to disable mangling?  I suspect that however minifify passes mange ops to uglify may suffers from this issue: https://github.com/mishoo/UglifyJS2/issues/378.  I get `Error` warnings on most files.

```js
// no workee
var compressOpts = {
    drop_debugger: false,
    unsafe: false,
    dead_code: true,
    mangle: false
};

// also no workee
var compressOptsDev = {
    drop_debugger: false,
    unsafe: false,
    dead_code: true,
    mangle: {
        sort: false,
        toplevel: false,
        eval: false
    }
};
```
