### ISSUE TITLE
dead code not removed

### ISSUE THREAD

**Issue by constantx** [ben-ng/minifyify#99]
I have this block of code being minifyify:

```js
var envConfig = (process.env.NODE_ENV === 'production')
  ? require('./config-production')
  : require('./config-development');
```

From the doc, I was expecting not to see `config-production` module in the bundle, but it's still there :( Any hint?

**Comment by ben-ng** [comment]
dead code removal depends on you using envify (because it replaces the envvar with a string literal). are you using envify?

if its not working after that, its probably and uglify problem. minifyify doesn't actually remove the dead code.

**Comment by constantx** [comment]
> minifyify doesn't actually remove the dead code.

ah, I must have had the wrong impression :) Gonna use envify now :)

:beers:
